### ISSUE TITLE
Pixels with RGB>0 and A=0 are still displayed

### ISSUE THREAD

**Issue by bathal1** [Tom94/tev#101]
Hi Thomas,
Opening the attached EXR file leads to an odd behavior in `tev`. The file contains pixels with non-zero RGB components and a zero alpha. Opening them in Photoshop or Gimp displays these pixels as fully transparent, while in `tev` these are partially visible. This behavior was observed using tev **1.16dev** on a **Ubuntu 18.04** machine.

EXR file:
[test.zip](https://github.com/Tom94/tev/files/4427909/test.zip)

**Comment by Tom94** [comment]
Hi Baptise,

this behavior is intentional, as the RGB values of EXR images should be interpreted as having pre-multiplied alpha. Photoshop and Gimp are wrong.

For a practical use case, consider composing the image of a flame onto some background. The alpha channel of the flame corresponds to its opacity, whereas the RGB channels correspond to its emitted light. Since flames don't really absorb light, their opacity---i.e. alpha channel---should be (roughly) zero, while the RGB values should still be very bright.

Check [this](https://github.com/AcademySoftwareFoundation/openexr-images/blob/master/ScanLines/CandleGlass.exr) example image of exactly the scenario I describe. The candle flame is meant to be visible despite its alpha value of zero.

See also the comment by Sami in issue #87 .

Cheers,
Thomas

**Comment by bathal1** [comment]
Alright, thanks for clarifying!
