### ISSUE TITLE
1mb limitation is a too small for large images

### ISSUE THREAD

**Issue by JiayinCao** [Tom94/tev#112]
Hi

I've been working on supporting TEV in my renderer.
https://sort-renderer.com/

And I noticed one limitation that is unnecessary to exist. Fixing it takes probably half an hour at most.
The size of this buffer 'mBuffer' in IPC is hard-coded as 1mb, this is not entirely necessary since you know the buffer size needed to hold all of the temporary memory when you receive a package from socket.
1 mb is can only update an image tile up to 256 x 256, this is nowhere near a full 1080p or 4k image.
So if I want to refresh half of my image, there is no easy way to do it without tiling that half image.

It would be nice to remove the limitation and have probably a way bigger limitation like 1GB in case it is really requested through socket.

Thanks

**Comment by Tom94** [comment]
You're completely right. Originally, IPC was based on UDP which placed size limitations on the individual packets... but with a streaming protocol like TCP, the OS handles large buffers just fine.

Thanks for pointing it out! The fix was indeed a delta of -3+2 lines of code. :)

I also quickly added a feature to update multiple image channels at once to prevent spectral flickering.
