### ISSUE TITLE
Keyboard shortcuts: shift does too many things

### ISSUE THREAD

**Issue by hjmallon** [Tom94/tev#123]
I'm enjoying tev, thanks for you work 🙏 . I am comparing EXRs by going into 'error' mode and pumping the Exposure using the 'E' key. However decrease exposure is 'Shift-E', but 'Shift' toggles the reference image as well.

Maybe 'Alt-E' could be added as an alternative to 'Shift-E' (or some other workaround)?

**Comment by Tom94** [comment]
Sorry for dragging my feet on this one; I agree. Fixed in the above: one must now hold 'Alt' to see the reference image.

The reason I was hesitant so far was that holding 'Alt' already did something else: it showed the tonemapped bytes instead of linear colors while zoomed in. But since that functionality is rarely needed (shown in the titlebar anyway), I remapped it to holding 'Shift+Ctrl'. Fingers crossed this doesn't spawn the next issue. :p
