### ISSUE TITLE
UI scaling on high-dpi screen

### ISSUE THREAD

**Issue by dvicini** [Tom94/tev#18]
Hi,
The UI does currently not seem to scale with higher DPI screens. I am using Arch Linux (KDE) and a 4K monitor. The KDE user interface scales nicely, but the tev interface becomes tiny.

I am not sure whether the underlying issue here is a nanogui problem, so feel free to close the issue if you think it should be fixed in nanogui itself. ;)
Delio

**Comment by Tom94** [comment]
Hi Delio,

this indeed is a problem at nanogui's end. Currently, on linux, it only obtains the pixel ratio via gsettings, so if you are not using gnome it probably won't work. Since tev is already using a fork of nanogui with some similar fixes implemented, I'll have a look at how easy scaling is to add for KDE. In case you want to look into it yourself, given that you are able to replicate the problem, [here](https://github.com/Tom94/nanogui/blob/master/src/screen.cpp#L68) is the file and function in question.

Cheers,
Thomas

**Comment by dvicini** [comment]
For reference, I commented on this in the nanogui main repository
https://github.com/wjakob/nanogui/issues/202

**Comment by Tom94** [comment]
Thanks for the help! I will test this locally on my machine and will merge afterwards. :)
