### ISSUE TITLE
Is Watch function working?

### ISSUE THREAD

**Issue by Naohiro2g** [Tom94/tev#236]
I tried the W for watch files in the folders to reload them automatically in vain. Is it working on Windows version??

When opening tev via cli, I got error messages like below and nothing happen when new file is added.

GLFW error 65544: WGL: Failed to make context current: The requested conversion operation is not supported.
GLFW error 65544: WGL: Failed to make context current: Handle invaild.

The last part of these messages are originally in Japanese.

I confirmed I don't see the messages in the case of launching tev as admin. And A (for all reload all) is only reloading files already loaded, not for new ones.

**Comment by Tom94** [comment]
Hi, if you'd like to watch a directory for file changes rather than just the already opened files, you need to load the directory rather than the files on startup, i.e.
```sh
tev --watch <directory name>
```
as opposed to
```sh
tev --watch <directory name>/*.exr
```
You can also drag the directory into an already open instance of **tev** to load all its images and then watch it with W.

Let me know if this helps!

**Comment by Naohiro2g** [comment]
@Tom94
Wow! Just great. 

I never knew the --watch option.
First, drag & drop worked fine then I tried the cli, which also worked successfully.

I just started Houdini and found tev to check the exr images during the long rendering. And it seems perfect for me now.
Regarding the GLFW error 65544, I see them in admin mode, too. It was not related to the admin/user, FYI.


Many thanks
