### ISSUE TITLE
tev unable to display a very simple png

### ISSUE THREAD

**Issue by mmp** [Tom94/tev#73]
(Not a big problem, but I thought I'd report it anyway.)

tev silently fails at displaying this image: ![kdwarp-0](https://user-images.githubusercontent.com/102567/59067407-6d1a6980-8866-11e9-85f9-f42b9bf6004c.png), which is a single-channel PNG with a single white scanline and is otherwise black.

Interestingly enough, It has no problem with this one, which is the same resolution, also single channel, and has a few more white scanlines: ![kdwarp-2](https://user-images.githubusercontent.com/102567/59067411-70155a00-8866-11e9-991f-8004324870f7.png)

**Comment by Tom94** [comment]
This one was quite interesting, thanks!

Turns out, your failing PNG file is _so small_ (just 102 bytes) that the file _type_ check (which is done prior to actual loading to determine which load-library to use) reaches EOF. tev didn't clear the EOF flag when seeking back to the beginning of the file, which led to load failure.

PS: In case you're on Windows, you can make such failures a little less silent by opening the console via F12. :)
